# Generated by Django 3.0.3 on 2020-10-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(max_length=20)),
                ('hum', models.FloatField(max_length=20)),
            ],
        ),
    ]
