# Generated by Django 3.0.3 on 2020-10-13 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datas',
            new_name='Monitor',
        ),
    ]
